version: 2
updates:
- package-ecosystem: nuget
  directory: "/samples/dotnetbot"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/dotnetsay"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/helloworld"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/helloworldasync"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/qotd"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
